### ISSUE TITLE
Feedback requested: Should block ids be removed?

### ISSUE THREAD

**Issue by KevinDaGame** [KevinDaGame/VoxelSniper#22]
Block ids are the old minecraft system of identifying blocks. This was removed in MC 1.13. Voxelsniper currently translates these old ids into the new blocks, but this list is outdated, does not always return the correct block in all situations and does not include any blocks since 1.13. Because of this, and because it might take some time to fix all the inconsistencies, we ask for feedback on whether this should be removed. Any comment is greatly appreciated.

**Comment by Seanoo1** [comment]
No it should not be remove. I am still be used to write glass with 20(and some code) so I don't want this feature remove.

**Comment by Lennart99** [comment]
Because of the amount of work required to keep supporting this (especially with #33), we have decided to remove this from the plugin.
